//! Go-executed vector tests for the MS-SMT leaf encoding of assets,
//! pinning Go's `Asset.Leaf()` (asset/asset.go): V1 assets strip the
//! raw `TxWitness` from the leaf value (Go `EncodeSegwit`, only the
//! witness sub-record type 3 is dropped; the PrevID and the
//! SplitCommitment sub-records are kept), while V0 assets use the full
//! encoding.
//!
//! The vector file `tests/testdata/asset_leaf_go_vectors.json` was
//! generated by executing Go against the tapd v0.8.99-alpha reference
//! (deterministic asset construction, no randomness), capturing:
//! - `expected`: `Asset.Encode()` (normal/full encoding) hex,
//! - `leaf_value`: `Asset.Leaf()` value bytes hex,
//! - `leaf_sum`: `Asset.Leaf()` MS-SMT sum.

mod common;

use common::*;
use serde::Deserialize;
use tap_primitives::asset::EncodeType;
use tap_primitives::encoding::asset::{
    asset_to_leaf, decode_asset, encode_asset, encode_asset_leaf,
};

#[derive(Debug, Deserialize)]
struct LeafVectorFile {
    #[allow(dead_code)]
    comment: String,
    valid_test_cases: Vec<LeafCase>,
}

#[derive(Debug, Deserialize)]
struct LeafCase {
    comment: String,
    asset: TestAsset,
    expected: String,
    leaf_value: String,
    leaf_sum: String,
}

#[test]
fn asset_leaf_go_vectors() {
    let file: LeafVectorFile = load_json("asset_leaf_go_vectors.json");
    assert_eq!(file.valid_test_cases.len(), 2);

    for case in &file.valid_test_cases {
        let comment = case.comment.as_str();

        // Construct the identical asset in Rust from the vector's
        // description (same schema as Go's asset/mock.go TestAsset).
        let asset = build_asset(&case.asset)
            .unwrap_or_else(|e| panic!("{}: build failed: {}", comment, e));

        // The full (normal) encoding must match Go's Asset.Encode().
        let full = encode_asset(&asset, EncodeType::Normal);
        assert_eq!(
            hex::encode(&full),
            case.expected,
            "{}: full encoding mismatch",
            comment
        );

        // The MS-SMT leaf must match Go's Asset.Leaf() byte for byte,
        // with the same sum.
        let leaf = asset_to_leaf(&asset)
            .unwrap_or_else(|e| panic!("{}: leaf failed: {}", comment, e));
        assert_eq!(
            hex::encode(&leaf.value),
            case.leaf_value,
            "{}: leaf value mismatch",
            comment
        );
        let expected_sum: u64 =
            case.leaf_sum.parse().expect("invalid leaf sum");
        assert_eq!(
            leaf.node_sum(),
            expected_sum,
            "{}: leaf sum mismatch",
            comment
        );

        // encode_asset_leaf is the underlying leaf-value encoder and
        // must agree.
        let leaf_bytes = encode_asset_leaf(&asset).unwrap();
        assert_eq!(hex::encode(&leaf_bytes), case.leaf_value, "{}", comment);

        // Decoding Go's full encoding and re-deriving the leaf must
        // produce the same result (decode -> leaf path).
        let decoded = decode_asset(&parse_hex(&case.expected))
            .unwrap_or_else(|e| panic!("{}: decode failed: {}", comment, e));
        let decoded_leaf = asset_to_leaf(&decoded).unwrap();
        assert_eq!(
            hex::encode(&decoded_leaf.value),
            case.leaf_value,
            "{}: decoded leaf value mismatch",
            comment
        );
        assert_eq!(decoded_leaf.node_sum(), expected_sum, "{}", comment);
    }

    // Cross-case structural checks pinning the headline behavior.
    let v1 = &file.valid_test_cases[0];
    let v0 = &file.valid_test_cases[1];
    assert_eq!(v1.asset.version, 1);
    assert_eq!(v0.asset.version, 0);

    // V1: the leaf value differs from the full encoding (the TxWitness
    // is stripped); V0: the leaf value IS the full encoding.
    assert_ne!(v1.leaf_value, v1.expected);
    assert_eq!(v0.leaf_value, v0.expected);

    // Both assets carry the same witness stack; the 64-byte 0x06
    // signature must appear in the full encodings and the V0 leaf but
    // not in the V1 leaf.
    let sig_hex = "06".repeat(64);
    assert!(v1.expected.contains(&sig_hex));
    assert!(v0.leaf_value.contains(&sig_hex));
    assert!(!v1.leaf_value.contains(&sig_hex));

    // The split commitment's root asset witness (64 bytes of 0x0e) is
    // encoded with the normal encoding inside the split commitment
    // sub-record (Go's SplitCommitmentEncoder always uses
    // RootAsset.Encode), so it is kept even in the V1 leaf.
    let root_sig_hex = "0e".repeat(64);
    assert!(v1.leaf_value.contains(&root_sig_hex));
    assert!(v0.leaf_value.contains(&root_sig_hex));
}
