//! Go-executed vector tests for `TxProof::verify`, pinning the
//! semantics of Go's `proof.TxProof.Verify` (proof/tx.go).
//!
//! The vector file `tests/testdata/tx_proof_verify_go_vectors.json`
//! was generated by executing Go against the tapd v0.8.99-alpha
//! reference: a deterministic synthetic block (coinbase + one segwit
//! P2TR transaction with three outputs) is built, the transaction
//! merkle proof is computed with Go's `proof.NewTxMerkleProof`, and
//! every `Verify` branch is exercised with the real
//! `proof.DefaultMerkleVerifier`:
//!
//! 1. claimed outpoint txid mismatch (`ErrHashMismatch`),
//! 2. output index out of range (`ErrOutputIndexInvalid`),
//! 3. claimed output script mismatch — non-P2TR output, wrong internal
//!    key, wrong/missing taproot merkle root
//!    (`ErrClaimedOutputScriptMismatch`),
//! 4. invalid transaction merkle proof — flipped direction bit,
//!    corrupted sibling node, wrong header merkle root
//!    (`ErrInvalidTxMerkleProof`),
//! 5. header verifier rejection,
//! 6. success for both BIP-86 and tapscript output constructions.
//!
//! NOTE: Go has no standalone binary encoding for `TxProof` (its wire
//! format is the `authmailboxrpc.BitcoinMerkleInclusionProof`
//! protobuf), so only the Verify semantics are Go-anchored here; the
//! rust-tap TLV framing is additionally round-tripped for each case.

mod common;

use common::*;
use serde::Deserialize;
use tap_primitives::asset::SerializedKey;
use tap_primitives::proof::types::AnchorTx;
use tap_primitives::proof::verify::{
    DefaultMerkleVerifier, HeaderVerifier, TrustAllHeaders,
};
use tap_primitives::proof::types::BlockHeader;
use tap_primitives::proof::{ProofError, TxProof};

#[derive(Debug, Deserialize)]
struct TxProofVectorFile {
    #[allow(dead_code)]
    comment: String,
    expected_txid: String,
    test_cases: Vec<TxProofVerifyCase>,
}

#[derive(Debug, Deserialize)]
struct TxProofVerifyCase {
    comment: String,
    proof: TestTxProofVector,
    reject_header: bool,
    expected_error: String,
}

#[derive(Debug, Deserialize)]
struct TestTxProofVector {
    raw_tx: String,
    block_header: TestBlockHeader,
    block_height: u32,
    merkle_proof: TestTxMerkleProof,
    claimed_outpoint: String,
    internal_key: String,
    merkle_root: String,
}

impl TestTxProofVector {
    fn to_tx_proof(&self) -> TxProof {
        TxProof {
            msg_tx: AnchorTx::from_bytes(&parse_hex(&self.raw_tx))
                .expect("invalid raw tx in vector"),
            block_header: self.block_header.to_block_header(),
            block_height: self.block_height,
            merkle_proof: self.merkle_proof.to_tx_merkle_proof(),
            claimed_outpoint: parse_out_point(&self.claimed_outpoint),
            internal_key: SerializedKey(parse_hex33(&self.internal_key)),
            merkle_root: if self.merkle_root.is_empty() {
                None
            } else {
                Some(parse_hex32(&self.merkle_root))
            },
        }
    }
}

/// A header verifier that always fails, standing in for Go's failing
/// `HeaderVerifier` callback in the vector's header-rejection case.
struct RejectAllHeaders;

impl HeaderVerifier for RejectAllHeaders {
    fn verify_header(
        &self,
        _header: &BlockHeader,
        _height: u32,
    ) -> Result<(), ProofError> {
        Err(ProofError::VerificationFailed("invalid header".into()))
    }
}

fn run_verify(
    proof: &TxProof,
    reject_header: bool,
) -> Result<(), ProofError> {
    if reject_header {
        proof.verify(&RejectAllHeaders, &DefaultMerkleVerifier)
    } else {
        proof.verify(&TrustAllHeaders, &DefaultMerkleVerifier)
    }
}

/// Asserts that the Rust outcome matches the Go sentinel error name
/// captured in the vector.
fn assert_outcome(
    result: Result<(), ProofError>,
    expected_error: &str,
    comment: &str,
) {
    match expected_error {
        "" => result.unwrap_or_else(|e| {
            panic!("{}: expected success, got {:?}", comment, e)
        }),
        "ErrHashMismatch" => assert!(
            matches!(result, Err(ProofError::HashMismatch)),
            "{}: expected HashMismatch, got {:?}",
            comment,
            result
        ),
        "ErrOutputIndexInvalid" => assert!(
            matches!(result, Err(ProofError::OutputIndexInvalid)),
            "{}: expected OutputIndexInvalid, got {:?}",
            comment,
            result
        ),
        "ErrClaimedOutputScriptMismatch" => assert!(
            matches!(
                result,
                Err(ProofError::ClaimedOutputScriptMismatch)
            ),
            "{}: expected ClaimedOutputScriptMismatch, got {:?}",
            comment,
            result
        ),
        "ErrInvalidTxMerkleProof" => assert!(
            matches!(result, Err(ProofError::InvalidTxMerkleProof)),
            "{}: expected InvalidTxMerkleProof, got {:?}",
            comment,
            result
        ),
        "header verifier error" => assert!(
            matches!(result, Err(ProofError::VerificationFailed(_))),
            "{}: expected VerificationFailed, got {:?}",
            comment,
            result
        ),
        other => panic!("unknown expected error {:?}", other),
    }
}

#[test]
fn tx_proof_verify_go_vectors() {
    let file: TxProofVectorFile =
        load_json("tx_proof_verify_go_vectors.json");
    assert_eq!(file.test_cases.len(), 12);

    // The Go-computed txid of the P2TR transaction (witness data
    // excluded from the hash even though the raw tx is serialized with
    // its witness).
    let expected_txid = parse_chain_hash(&file.expected_txid);

    let mut successes = 0;
    for case in &file.test_cases {
        let comment = case.comment.as_str();
        let proof = case.proof.to_tx_proof();

        assert_eq!(
            proof.msg_tx.txid(),
            expected_txid,
            "{}: txid mismatch vs Go's wire.MsgTx.TxHash",
            comment
        );

        let result = run_verify(&proof, case.reject_header);
        assert_outcome(result, &case.expected_error, comment);
        if case.expected_error.is_empty() {
            successes += 1;
        }

        // The rust-tap internal TLV framing must round-trip each case
        // and preserve the verification outcome.
        let decoded = TxProof::decode(&proof.encode())
            .unwrap_or_else(|e| panic!("{}: decode failed: {}", comment, e));
        assert_eq!(proof, decoded, "{}: TLV round-trip mismatch", comment);
        let result = run_verify(&decoded, case.reject_header);
        assert_outcome(result, &case.expected_error, comment);
    }

    // The vector carries both success constructions (BIP-86 and
    // tapscript merkle root).
    assert_eq!(successes, 2);
}
