// This file is Copyright its original authors, visible in version control
// history.
//
// This file is licensed under the Apache License, Version 2.0 <LICENSE-APACHE
// or http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your option.
// You may not use this file except in accordance with one or both of these
// licenses.

//! End-to-end receive-then-send over functional fakes: a sender node
//! mints and sends to an address generated by a RECEIVER node
//! (`new_address`, the V0 path); the receiver imports the delivered
//! proof and then sends the asset onward, signing with the key
//! descriptor stored when the address was generated.

mod common;

use std::collections::BTreeMap;

use common::*;

use tap_node::*;
use tap_onchain::proof::courier::{Courier, CourierLocator, Recipient};
use tap_primitives::address::{AddressVersion, TapAddress, TapNetwork};
use tap_primitives::asset::{OutPoint, ScriptKey};
use tap_primitives::proof::{
    BlockHeader, ChainLookup, DefaultMerkleVerifier, GroupVerifier,
    HeaderVerifier, NoIgnoreChecker, ProofError, ProofVerificationOptions,
    VerifierCtx,
};

// -- Full proof verifier (accept headers/groups, real Schnorr witness
// and commitment verification, chain checks skipped because the fakes
// anchor in synthetic blocks), matching the send_flow tests. --

struct AcceptHeaders;
impl HeaderVerifier for AcceptHeaders {
    fn verify_header(
        &self,
        _header: &BlockHeader,
        _height: u32,
    ) -> Result<(), ProofError> {
        Ok(())
    }
}

struct AcceptGroups;
impl GroupVerifier for AcceptGroups {
    fn verify_group_key(
        &self,
        _group_key: &SerializedKey,
    ) -> Result<(), ProofError> {
        Ok(())
    }
}

struct MockLookup;
impl ChainLookup for MockLookup {
    fn current_height(&self) -> Result<u32, ProofError> {
        Ok(900_000)
    }
}

fn verifier_ctx() -> VerifierCtx<
    AcceptHeaders,
    DefaultMerkleVerifier,
    AcceptGroups,
    MockLookup,
    NoIgnoreChecker,
> {
    VerifierCtx::new(
        AcceptHeaders,
        DefaultMerkleVerifier,
        AcceptGroups,
        MockLookup,
    )
}

fn verify_opts() -> ProofVerificationOptions {
    ProofVerificationOptions {
        challenge_bytes: None,
        skip_chain_verification: true,
        skip_time_lock_validation: false,
    }
}

/// A recipient address over keys unrelated to either node's key ring.
fn foreign_address(asset_id: AssetId, amount: u64) -> TapAddress {
    TapAddress {
        version: AddressVersion::V0,
        asset_version: 0,
        asset_id: Some(asset_id),
        script_key: FakeKeys::pub_key_for(100),
        internal_key: FakeKeys::pub_key_for(101),
        amount,
        network: TapNetwork::Regtest,
        proof_courier_addr: Some("hashmail://courier.test:8080".into()),
        group_key: None,
        tapscript_sibling: None,
        unknown_odd_types: BTreeMap::new(),
    }
}

/// A received asset must be spendable: the address book keeps the key
/// descriptors behind `new_address` script keys, the proof import
/// attaches them (plus the genesis fields and the verified block
/// height) to the imported asset, and an onward send signs with them.
#[test]
fn test_received_asset_can_be_sent_onward() {
    // The receiver's config carries a courier URL so its addresses ask
    // for proof delivery.
    let mut receiver_config = TapNodeConfig::default();
    receiver_config.courier_url = "hashmail://courier.test:8080".into();

    let sender = default_harness();
    let receiver = build_harness(receiver_config);

    // -- Sender: mint and confirm 1000 units. --
    sender
        .node
        .queue_mint(tap_onchain::mint::Seedling::new_normal(
            "recv-token".into(),
            1_000,
        ))
        .expect("queue");
    let mint = sender.node.finalize_mint().expect("finalize");
    sender.chain.confirm_tx(&mint.signed_tx, 812_000);
    let summary = sender.node.tick().expect("tick");
    assert_eq!(summary.confirmed_anchors, 1);
    assert!(summary.errors.is_empty(), "{:?}", summary.errors);
    let asset_id = mint.assets[0].asset_id;

    // -- Receiver: generate a V0 address. The script key is the
    // BIP-86 tweak of a key derived from the receiver's key ring. --
    let addr = receiver.node.new_address(asset_id, 400).expect("address");
    assert!(addr.proof_courier_addr.is_some());

    // -- Sender: send 400 to the address and confirm. --
    let handle = sender
        .node
        .send_asset(asset_id, 400, &addr)
        .expect("send to receiver");
    let broadcast = sender.chain.last_broadcast().expect("broadcast");
    sender.chain.confirm_tx(&broadcast, 812_500);
    let summary = sender.node.tick().expect("tick");
    assert_eq!(summary.confirmed_anchors, 1);
    assert!(summary.errors.is_empty(), "{:?}", summary.errors);

    // -- Receiver: fetch the delivered proof from the courier (the
    // shared mock courier stands in for the receiver's transport) and
    // import it. --
    let recipient_outpoint = OutPoint {
        txid: to_internal(handle.txid),
        vout: 1,
    };
    let delivered = sender
        .courier
        .receive_proof(
            &Recipient {
                script_key: addr.script_key,
                asset_id,
                amount: 400,
            },
            &CourierLocator {
                asset_id,
                script_key: addr.script_key,
                outpoint: recipient_outpoint,
            },
        )
        .expect("proof delivered");
    receiver
        .node
        .import_proof(delivered.proof_file)
        .expect("import");

    // The import attached the signing context, the genesis fields,
    // and the verified block height.
    let owned_list = receiver.node.list_assets().expect("list");
    assert_eq!(owned_list.len(), 1);
    let owned = &owned_list[0];
    assert_eq!(owned.asset_id, asset_id);
    assert_eq!(owned.amount, 400);
    assert_eq!(owned.script_key, addr.script_key);
    assert_eq!(owned.anchor_outpoint, recipient_outpoint);
    assert_eq!(owned.block_height, 812_500);
    let desc = owned
        .script_key_desc
        .as_ref()
        .expect("script key descriptor attached on import");
    assert_eq!(ScriptKey::bip86(desc.pub_key).pub_key, addr.script_key);
    let internal = owned
        .internal_key
        .as_ref()
        .expect("internal key descriptor attached on import");
    assert_eq!(internal.pub_key, addr.internal_key);
    assert_eq!(owned.genesis_tag.as_deref(), Some("recv-token"));
    assert_eq!(owned.genesis_point, Some(mint.genesis_point));
    assert_eq!(receiver.node.get_balance(&asset_id).expect("bal"), 400);

    // AssetReceived carried the real values (no placeholder zeros).
    let events = receiver.drain_events();
    assert!(events.iter().any(|e| matches!(
        e,
        TapEvent::AssetReceived {
            amount: 400,
            outpoint,
            ..
        } if *outpoint == recipient_outpoint
    )));

    // -- Receiver: send 150 onward. Signing resolves the imported
    // descriptor (previously this failed with UnknownScriptKey). --
    let onward = foreign_address(asset_id, 150);
    let handle2 = receiver
        .node
        .send_asset(asset_id, 150, &onward)
        .expect("onward send signs with the imported descriptor");
    assert_eq!(receiver.node.get_balance(&asset_id).expect("bal"), 250);

    let broadcast = receiver.chain.last_broadcast().expect("broadcast");
    receiver.chain.confirm_tx(&broadcast, 812_600);
    let summary = receiver.node.tick().expect("tick");
    assert_eq!(summary.confirmed_anchors, 1);
    assert!(summary.errors.is_empty(), "{:?}", summary.errors);

    // The onward recipient proof carries the full provenance
    // (genesis -> hop 1 -> hop 2) and passes the full verifier,
    // proving the signature over the received asset is real.
    let onward_outpoint = OutPoint {
        txid: to_internal(handle2.txid),
        vout: 1,
    };
    let file = receiver
        .node
        .export_proof(&onward_outpoint, &onward.script_key)
        .expect("onward proof stored");
    assert_eq!(file.num_proofs(), 3);
    assert!(file.verify_hash_chain());
    file.verify(&verifier_ctx(), &verify_opts())
        .expect("onward proof must fully verify");
}
