// This file is Copyright its original authors, visible in version control
// history.
//
// This file is licensed under the Apache License, Version 2.0 <LICENSE-APACHE
// or http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your option.
// You may not use this file except in accordance with one or both of these
// licenses.

//! End-to-end receive-then-send over functional fakes: a sender node
//! mints and sends to an address generated by a RECEIVER node
//! (`new_address`, the V0 path); the receiver imports the delivered
//! proof and then sends the asset onward, signing with the key
//! descriptor stored when the address was generated.

mod common;

use std::collections::BTreeMap;

use common::*;

use tap_node::*;
use tap_onchain::proof::courier::{Courier, CourierLocator, Recipient};
use tap_primitives::address::{AddressVersion, TapAddress, TapNetwork};
use tap_primitives::asset::{OutPoint, ScriptKey};
use tap_primitives::proof::{
    BlockHeader, ChainLookup, DefaultMerkleVerifier, GroupVerifier,
    HeaderVerifier, NoIgnoreChecker, ProofError, ProofVerificationOptions,
    VerifierCtx,
};

// -- Full proof verifier (accept headers/groups, real Schnorr witness
// and commitment verification, chain checks skipped because the fakes
// anchor in synthetic blocks), matching the send_flow tests. --

struct AcceptHeaders;
impl HeaderVerifier for AcceptHeaders {
    fn verify_header(
        &self,
        _header: &BlockHeader,
        _height: u32,
    ) -> Result<(), ProofError> {
        Ok(())
    }
}

struct AcceptGroups;
impl GroupVerifier for AcceptGroups {
    fn verify_group_key(
        &self,
        _group_key: &SerializedKey,
    ) -> Result<(), ProofError> {
        Ok(())
    }
}

struct MockLookup;
impl ChainLookup for MockLookup {
    fn current_height(&self) -> Result<u32, ProofError> {
        Ok(900_000)
    }
}

fn verifier_ctx() -> VerifierCtx<
    AcceptHeaders,
    DefaultMerkleVerifier,
    AcceptGroups,
    MockLookup,
    NoIgnoreChecker,
> {
    VerifierCtx::new(
        AcceptHeaders,
        DefaultMerkleVerifier,
        AcceptGroups,
        MockLookup,
    )
}

fn verify_opts() -> ProofVerificationOptions {
    ProofVerificationOptions {
        challenge_bytes: None,
        skip_chain_verification: true,
        skip_time_lock_validation: false,
    }
}

/// A recipient address over keys unrelated to either node's key ring.
fn foreign_address(asset_id: AssetId, amount: u64) -> TapAddress {
    TapAddress {
        version: AddressVersion::V0,
        asset_version: 0,
        asset_id: Some(asset_id),
        script_key: FakeKeys::pub_key_for(100),
        internal_key: FakeKeys::pub_key_for(101),
        amount,
        network: TapNetwork::Regtest,
        proof_courier_addr: Some("hashmail://courier.test:8080".into()),
        group_key: None,
        tapscript_sibling: None,
        unknown_odd_types: BTreeMap::new(),
    }
}

/// A received asset must be spendable: the address book keeps the key
/// descriptors behind `new_address` script keys, the proof import
/// attaches them (plus the genesis fields and the verified block
/// height) to the imported asset, and an onward send signs with them.
#[test]
fn test_received_asset_can_be_sent_onward() {
    // The receiver's config carries a courier URL so its addresses ask
    // for proof delivery.
    let mut receiver_config = TapNodeConfig::default();
    receiver_config.courier_url = "hashmail://courier.test:8080".into();

    let sender = default_harness();
    let receiver = build_harness(receiver_config);

    // -- Sender: mint and confirm 1000 units. --
    sender
        .node
        .queue_mint(tap_onchain::mint::Seedling::new_normal(
            "recv-token".into(),
            1_000,
        ))
        .expect("queue");
    let mint = sender.node.finalize_mint().expect("finalize");
    sender.chain.confirm_tx(&mint.signed_tx, 812_000);
    let summary = sender.node.tick().expect("tick");
    assert_eq!(summary.confirmed_anchors, 1);
    assert!(summary.errors.is_empty(), "{:?}", summary.errors);
    let asset_id = mint.assets[0].asset_id;

    // -- Receiver: generate a V0 address. The script key is the
    // BIP-86 tweak of a key derived from the receiver's key ring. --
    let addr = receiver.node.new_address(asset_id, 400).expect("address");
    assert!(addr.proof_courier_addr.is_some());

    // -- Sender: send 400 to the address and confirm. --
    let handle = sender
        .node
        .send_asset(asset_id, 400, &addr)
        .expect("send to receiver");
    let broadcast = sender.chain.last_broadcast().expect("broadcast");
    sender.chain.confirm_tx(&broadcast, 812_500);
    let summary = sender.node.tick().expect("tick");
    assert_eq!(summary.confirmed_anchors, 1);
    assert!(summary.errors.is_empty(), "{:?}", summary.errors);

    // -- Receiver: fetch the delivered proof from the courier (the
    // shared mock courier stands in for the receiver's transport) and
    // import it. --
    let recipient_outpoint = OutPoint {
        txid: to_internal(handle.txid),
        vout: 1,
    };
    let delivered = sender
        .courier
        .receive_proof(
            &Recipient {
                script_key: addr.script_key,
                asset_id,
                amount: 400,
            },
            &CourierLocator {
                asset_id,
                script_key: addr.script_key,
                outpoint: recipient_outpoint,
            },
        )
        .expect("proof delivered");
    receiver
        .node
        .import_proof(delivered.proof_file)
        .expect("import");

    // The import attached the signing context, the genesis fields,
    // and the verified block height.
    let owned_list = receiver.node.list_assets().expect("list");
    assert_eq!(owned_list.len(), 1);
    let owned = &owned_list[0];
    assert_eq!(owned.asset_id, asset_id);
    assert_eq!(owned.amount, 400);
    assert_eq!(owned.script_key, addr.script_key);
    assert_eq!(owned.anchor_outpoint, recipient_outpoint);
    assert_eq!(owned.block_height, 812_500);
    let desc = owned
        .script_key_desc
        .as_ref()
        .expect("script key descriptor attached on import");
    assert_eq!(ScriptKey::bip86(desc.pub_key).pub_key, addr.script_key);
    let internal = owned
        .internal_key
        .as_ref()
        .expect("internal key descriptor attached on import");
    assert_eq!(internal.pub_key, addr.internal_key);
    assert_eq!(owned.genesis_tag.as_deref(), Some("recv-token"));
    assert_eq!(owned.genesis_point, Some(mint.genesis_point));
    assert_eq!(receiver.node.get_balance(&asset_id).expect("bal"), 400);

    // AssetReceived carried the real values (no placeholder zeros).
    let events = receiver.drain_events();
    assert!(events.iter().any(|e| matches!(
        e,
        TapEvent::AssetReceived {
            amount: 400,
            outpoint,
            ..
        } if *outpoint == recipient_outpoint
    )));

    // -- Receiver: send 150 onward. Signing resolves the imported
    // descriptor (previously this failed with UnknownScriptKey). --
    let onward = foreign_address(asset_id, 150);
    let handle2 = receiver
        .node
        .send_asset(asset_id, 150, &onward)
        .expect("onward send signs with the imported descriptor");
    assert_eq!(receiver.node.get_balance(&asset_id).expect("bal"), 250);

    let broadcast = receiver.chain.last_broadcast().expect("broadcast");
    receiver.chain.confirm_tx(&broadcast, 812_600);
    let summary = receiver.node.tick().expect("tick");
    assert_eq!(summary.confirmed_anchors, 1);
    assert!(summary.errors.is_empty(), "{:?}", summary.errors);

    // The onward recipient proof carries the full provenance
    // (genesis -> hop 1 -> hop 2) and passes the full verifier,
    // proving the signature over the received asset is real.
    let onward_outpoint = OutPoint {
        txid: to_internal(handle2.txid),
        vout: 1,
    };
    let file = receiver
        .node
        .export_proof(&onward_outpoint, &onward.script_key)
        .expect("onward proof stored");
    assert_eq!(file.num_proofs(), 3);
    assert!(file.verify_hash_chain());
    file.verify(&verifier_ctx(), &verify_opts())
        .expect("onward proof must fully verify");
}

/// Builds a valid tx proof over a synthetic single-tx block whose only
/// output is a BIP-86 P2TR output for the given anchor key. Serves as
/// the mailbox server's proof-of-work; the send fragment inside the
/// message carries the real anchor outpoint.
fn synthetic_tx_proof(
    anchor_internal_key: SerializedKey,
    height: u32,
) -> tap_primitives::proof::TxProof {
    use bitcoin::absolute::LockTime;
    use bitcoin::transaction::Version;
    use bitcoin::{Amount, ScriptBuf, Transaction, TxOut};
    use tap_primitives::crypto::tapscript::taproot_output_key;
    use tap_primitives::proof::types::AnchorTx;

    let output_key =
        taproot_output_key(&anchor_internal_key, &[]).expect("output key");
    let mut script = Vec::with_capacity(34);
    script.push(0x51);
    script.push(0x20);
    script.extend_from_slice(&output_key);

    let tx = AnchorTx(Transaction {
        version: Version(2),
        lock_time: LockTime::ZERO,
        input: vec![],
        output: vec![TxOut {
            value: Amount::from_sat(1000),
            script_pubkey: ScriptBuf::from_bytes(script),
        }],
    });
    let txid = tx.txid();

    // Single-tx block: the header's merkle root is the txid itself.
    let mut header_bytes = [0u8; 80];
    header_bytes[36..68].copy_from_slice(&txid);

    tap_onchain::proof::mailbox::build_tx_proof(
        tx,
        BlockHeader(header_bytes),
        height,
        &[txid],
        0,
        anchor_internal_key,
        None,
    )
    .expect("tx proof builds")
}

/// End-to-end V2 (authmailbox) receive-then-send: a sender node mints
/// and sends to the unique per-asset-ID Pedersen script key of a V2
/// address generated by a receiver node; the receiver polls the
/// mailbox, imports the transfer, and then sends the asset ONWARD.
///
/// The onward send exercises the tapscript-tweak-aware signer seam
/// (`AssetSigner::sign_virtual_tx_tweaked`): the input's script key is
/// the address key tweaked with the Pedersen leaf's tap hash, so the
/// signer must apply the BIP-341 `TapTweakHash(address_key, root)`
/// tweak. The resulting proof file passes the full verifier with real
/// Schnorr validation, which is the oracle for the tweak chain: a
/// wrong tweak yields an invalid signature the vm rejects.
#[test]
fn test_v2_received_asset_can_be_sent_onward() {
    use std::collections::BTreeMap as Map;

    use tap_node::receive::V2AddressParams;
    use tap_onchain::proof::mailbox::{
        build_send_fragment, deliver_send_manifest, SendManifest,
    };
    use tap_primitives::asset::{AssetType, AssetVersion};
    use tap_primitives::proof::send_fragment::SendOutput;

    const COURIER_URL: &str =
        "authmailbox+universerpc://courier.test:10029";

    let sender = default_harness();

    let mut receiver_config = TapNodeConfig::default();
    receiver_config.courier_url = COURIER_URL.into();
    let (receiver, transport) = build_mailbox_harness(receiver_config);

    // -- Sender: mint and confirm 1000 units. --
    sender
        .node
        .queue_mint(tap_onchain::mint::Seedling::new_normal(
            "v2-token".into(),
            1_000,
        ))
        .expect("queue");
    let mint = sender.node.finalize_mint().expect("finalize");
    sender.chain.confirm_tx(&mint.signed_tx, 812_000);
    let summary = sender.node.tick().expect("tick");
    assert_eq!(summary.confirmed_anchors, 1);
    assert!(summary.errors.is_empty(), "{:?}", summary.errors);
    let asset_id = mint.assets[0].asset_id;

    // -- Receiver: generate a V2 address. Assets sent to it land
    // under the unique per-asset-ID Pedersen script key derived from
    // the address script key. --
    let addr = receiver
        .node
        .new_address_v2(V2AddressParams {
            asset_id: Some(asset_id),
            group_key: None,
            amount: 0,
            asset_type: AssetType::Normal,
        })
        .expect("v2 address");
    let unique_key = addr
        .script_key_for_asset_id(&asset_id)
        .expect("unique script key");
    assert_ne!(unique_key, addr.script_key);

    // -- Sender: send 400 to the receiver's unique script key (what a
    // V2-aware sender derives from the address) and confirm. --
    let to_receiver = TapAddress {
        version: AddressVersion::V0,
        asset_version: 0,
        asset_id: Some(asset_id),
        script_key: unique_key,
        internal_key: addr.internal_key,
        amount: 400,
        network: TapNetwork::Regtest,
        proof_courier_addr: Some("hashmail://courier.test:8080".into()),
        group_key: None,
        tapscript_sibling: None,
        unknown_odd_types: BTreeMap::new(),
    };
    let handle = sender
        .node
        .send_asset(asset_id, 400, &to_receiver)
        .expect("send to V2 script key");
    let broadcast = sender.chain.last_broadcast().expect("broadcast");
    sender.chain.confirm_tx(&broadcast, 812_500);
    let summary = sender.node.tick().expect("tick");
    assert_eq!(summary.confirmed_anchors, 1);
    assert!(summary.errors.is_empty(), "{:?}", summary.errors);

    let recipient_outpoint = OutPoint {
        txid: to_internal(handle.txid),
        vout: 1,
    };

    // -- Wire the transfer proof from the sender's courier into the
    // receiver's courier (the two harnesses stand in for a shared
    // universe courier). --
    let recipient = Recipient {
        script_key: unique_key,
        asset_id,
        amount: 400,
    };
    let locator = CourierLocator {
        asset_id,
        script_key: unique_key,
        outpoint: recipient_outpoint,
    };
    let delivered = sender
        .courier
        .receive_proof(&recipient, &locator)
        .expect("proof delivered by sender");
    assert_eq!(delivered.proof_file.num_proofs(), 2);
    receiver
        .courier
        .deliver_proof(&recipient, &delivered)
        .expect("stage proof for receiver");

    // -- Sender: deliver the send manifest through the auth mailbox.
    // The tx proof (mailbox proof-of-work) is over a synthetic block;
    // the fragment carries the real anchor outpoint and a header the
    // receiver's chain can verify. --
    let height = 812_500u32;
    let tx_proof = synthetic_tx_proof(FakeKeys::pub_key_for(50), height);
    let header = tx_proof.block_header.clone();
    receiver.chain.set_block_hash(height, header.block_hash());

    let fragment = build_send_fragment(
        header,
        height,
        recipient_outpoint,
        [0xAB; 32],
        Map::from([(
            asset_id,
            SendOutput {
                asset_version: AssetVersion::V0,
                amount: 400,
                derivation_method:
                    tap_primitives::asset::ScriptKeyDerivationMethod::UniquePedersen,
                script_key: unique_key,
            },
        )]),
    )
    .expect("fragment builds");
    deliver_send_manifest(
        &*transport,
        &SendManifest {
            tx_proof,
            receiver: addr.script_key,
            courier_url: COURIER_URL.to_string(),
            fragment,
        },
    )
    .expect("manifest delivered");

    // -- Receiver: poll the mailbox and import the transfer. --
    let received = receiver.node.poll_mailbox().expect("poll");
    assert_eq!(received.len(), 1);
    assert_eq!(received[0].asset_id, asset_id);
    assert_eq!(received[0].amount, 400);
    assert_eq!(received[0].script_key, unique_key);
    assert_eq!(received[0].anchor_outpoint, recipient_outpoint);
    assert_eq!(receiver.node.get_balance(&asset_id).expect("bal"), 400);

    // The imported asset is held under the unique Pedersen script key
    // with the ADDRESS script key's descriptor as signing context (the
    // raw key the unique key is derived from).
    let owned_list = receiver.node.list_assets().expect("list");
    assert_eq!(owned_list.len(), 1);
    let owned = &owned_list[0];
    assert_eq!(owned.script_key, unique_key);
    let desc = owned
        .script_key_desc
        .as_ref()
        .expect("address key descriptor attached");
    assert_eq!(desc.pub_key, addr.script_key);

    // -- Receiver: send 150 onward. Signing must apply the BIP-341
    // tweak with the Pedersen leaf tap hash as the tapscript root
    // (AssetSigner::sign_virtual_tx_tweaked). --
    let onward = foreign_address(asset_id, 150);
    let handle2 = receiver
        .node
        .send_asset(asset_id, 150, &onward)
        .expect("onward send signs the V2 unique script key");
    assert_eq!(receiver.node.get_balance(&asset_id).expect("bal"), 250);

    let broadcast = receiver.chain.last_broadcast().expect("broadcast");
    receiver.chain.confirm_tx(&broadcast, 812_600);
    let summary = receiver.node.tick().expect("tick");
    assert_eq!(summary.confirmed_anchors, 1);
    assert!(summary.errors.is_empty(), "{:?}", summary.errors);

    // The onward recipient proof carries the full provenance
    // (genesis -> V2 hop -> onward hop) and passes the full verifier
    // with real Schnorr validation. This is the oracle for the tweak
    // chain: the onward transition's witness is a key-spend signature
    // against the unique Pedersen script key, so a wrong taproot
    // tweak (e.g. plain BIP-86) would make the vm reject the proof.
    let onward_outpoint = OutPoint {
        txid: to_internal(handle2.txid),
        vout: 1,
    };
    let file = receiver
        .node
        .export_proof(&onward_outpoint, &onward.script_key)
        .expect("onward proof stored");
    assert_eq!(file.num_proofs(), 3);
    assert!(file.verify_hash_chain());
    file.verify(&verifier_ctx(), &verify_opts())
        .expect("onward proof over a V2 input must fully verify");

    // The receiver's change output (fresh BIP-86 key) also proves out.
    let change_assets = receiver.node.list_assets().expect("list");
    let change = change_assets
        .iter()
        .find(|a| !a.spent && a.amount == 250)
        .expect("change output persisted");
    let change_file = receiver
        .node
        .export_proof(&change.anchor_outpoint, &change.script_key)
        .expect("change proof stored");
    change_file
        .verify(&verifier_ctx(), &verify_opts())
        .expect("change proof must fully verify");
}
