//! Golden fixture tests against the Go taproot-assets wire format.
//!
//! The fixtures under `tests/testdata/compat/v0.8/` are vendored
//! verbatim from the Go repository:
//! - `rfqmsg/testdata/compat/v0.8/{request,accept,reject,htlc}.hex`
//!   (deterministic fixtures generated by Go's
//!   `TestGenerateCompatFixtures`)
//! - `tapchannelmsg/testdata/compat/v0.8/*.hexdump` (captures from real
//!   protocol interactions)
//!
//! For the deterministic rfqmsg fixtures we assert full round trips:
//! decode -> re-encode -> byte equality. For the tapchannelmsg hexdump
//! captures Go itself only asserts decode (optional-record and map
//! iteration order make byte equality impossible to guarantee), so we
//! assert decode -> encode -> decode field equality instead.

use tap_ldk::channel::blobs::{ChannelBlob, CommitmentBlob};
use tap_ldk::rfq::FixedPoint;
use tap_ldk::routing::AssetHtlcData;
use tap_ldk::wire::compat::{
    AcceptWireMsg, RejectCode, RejectWireMsg, RequestWireMsg,
};

fn fixture_path(name: &str) -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/testdata/compat/v0.8")
        .join(name)
}

fn decode_hex(s: &str) -> Vec<u8> {
    let s: String = s.chars().filter(|c| !c.is_whitespace()).collect();
    assert!(s.len() % 2 == 0, "odd hex length");
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("bad hex"))
        .collect()
}

/// Loads a `.hex` fixture (a single hex string).
fn load_hex_fixture(name: &str) -> Vec<u8> {
    let content =
        std::fs::read_to_string(fixture_path(name)).expect("fixture exists");
    decode_hex(content.trim())
}

/// Loads a `.hexdump` fixture (output of `hexdump -C`): per line, an
/// offset, up to 16 hex byte pairs, and an `|ascii|` column. Mirrors
/// Go's `ExtractHexDump`.
fn load_hexdump_fixture(name: &str) -> Vec<u8> {
    let content =
        std::fs::read_to_string(fixture_path(name)).expect("fixture exists");
    let mut bytes = Vec::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        // Strip the ascii column.
        let hex_part = match line.find('|') {
            Some(pos) => &line[..pos],
            None => line,
        };
        let mut tokens = hex_part.split_whitespace();
        // First token is the offset; skip it.
        let _offset = tokens.next();
        for token in tokens {
            if token.len() == 2 {
                if let Ok(b) = u8::from_str_radix(token, 16) {
                    bytes.push(b);
                }
            }
        }
    }
    bytes
}

#[test]
fn test_request_fixture_roundtrip() {
    let data = load_hex_fixture("request.hex");
    let msg = RequestWireMsg::decode(&data).expect("decode request fixture");

    assert_eq!(msg.version, 1);
    assert_eq!(msg.id, [0xAA; 32]);
    // The Go fixture generator leaves the transfer type at its zero
    // value (UnspecifiedTransferType).
    assert_eq!(msg.transfer_type, 0);
    assert_eq!(msg.expiry, 4_102_444_800);
    assert_eq!(msg.in_asset_id, Some([0xBB; 32]));
    assert_eq!(msg.out_asset_id, Some([0u8; 32]));
    assert_eq!(msg.max_in_asset, 50_000);
    assert_eq!(msg.in_asset_group_key, None);
    assert_eq!(msg.out_asset_group_key, None);
    assert_eq!(msg.in_asset_rate_hint, None);
    assert_eq!(msg.out_asset_rate_hint, None);
    assert_eq!(msg.min_in_asset, None);
    assert_eq!(msg.min_out_asset, None);

    // Byte-exact re-encode.
    assert_eq!(msg.encode().expect("encode"), data);
}

#[test]
fn test_accept_fixture_roundtrip() {
    let data = load_hex_fixture("accept.hex");
    let msg = AcceptWireMsg::decode(&data).expect("decode accept fixture");

    assert_eq!(msg.version, 1);
    assert_eq!(msg.id, [0xAA; 32]);
    assert_eq!(msg.expiry, 4_102_444_800);
    assert_eq!(msg.sig, [0xCC; 64]);
    // In rate: scale 2, coefficient 42000; out rate: scale 0, coeff 1.
    assert_eq!(msg.in_asset_rate, FixedPoint::new(42_000, 2));
    assert_eq!(msg.out_asset_rate, FixedPoint::new(1, 0));
    assert_eq!(msg.max_in_asset, None);

    assert_eq!(msg.encode().expect("encode"), data);
}

#[test]
fn test_reject_fixture_roundtrip() {
    let data = load_hex_fixture("reject.hex");
    let msg = RejectWireMsg::decode(&data).expect("decode reject fixture");

    assert_eq!(msg.version, 1);
    assert_eq!(msg.id, [0xAA; 32]);
    assert_eq!(msg.code, RejectCode::PriceOracleUnavailable);
    assert_eq!(msg.message, "rates expired");

    assert_eq!(msg.encode().expect("encode"), data);
}

#[test]
fn test_htlc_fixture_roundtrip() {
    let data = load_hex_fixture("htlc.hex");
    let htlc = AssetHtlcData::decode(&data).expect("decode htlc fixture");

    assert_eq!(htlc.balances.len(), 1);
    assert_eq!(htlc.balances[0].asset_id.0, [0xBB; 32]);
    assert_eq!(htlc.balances[0].amount, 1000);
    assert_eq!(htlc.rfq_id, Some([0xAA; 32]));

    // Byte-exact re-encode: the record set (65536, 65538) is fully
    // deterministic.
    assert_eq!(htlc.encode(), data);
}

#[test]
fn test_funding_blob_fixture_decodes() {
    let data = load_hexdump_fixture("funding-blob.hexdump");
    let blob = ChannelBlob::decode(&data).expect("decode funding blob");

    assert!(
        !blob.funded_assets.is_empty(),
        "funding blob should contain assets"
    );
    // Every funded asset must carry its proof (Go requires it).
    for asset in &blob.funded_assets {
        assert!(asset.proof.is_some());
        assert!(asset.amount > 0);
    }

    // Re-encode and decode again: field equality (Go does not assert
    // byte equality for these captured fixtures either).
    let reencoded = blob.encode().expect("re-encode");
    let decoded2 = ChannelBlob::decode(&reencoded).expect("decode again");
    assert_eq!(blob, decoded2);
}

#[test]
fn test_commitment_blob_fixture_decodes() {
    let data = load_hexdump_fixture("commitment-blob.hexdump");
    let blob = CommitmentBlob::decode(&data).expect("decode commitment blob");

    // Access the balance fields (mirrors the Go compat test).
    let _ = blob.local_balance();
    let _ = blob.remote_balance();

    let reencoded = blob.encode().expect("re-encode");
    let decoded2 = CommitmentBlob::decode(&reencoded).expect("decode again");
    assert_eq!(blob, decoded2);
}

#[test]
fn test_htlc_blob_fixture_decodes() {
    let data = load_hexdump_fixture("htlc-blob.hexdump");
    let htlc = AssetHtlcData::decode(&data).expect("decode htlc blob");

    // The fixture may have zero balances if it represents a no-op
    // HTLC (mirrors the Go compat test); just re-encode and decode.
    let reencoded = htlc.encode();
    if reencoded.is_empty() {
        // Both records absent: nothing further to check.
        return;
    }
    let decoded2 = AssetHtlcData::decode(&reencoded).expect("decode again");
    assert_eq!(htlc, decoded2);
}
